### ISSUE TITLE
Permission denied on `json-schemas`

### ISSUE THREAD

**Issue by rgstephens** [deepset-ai/haystack-demos#1]
Hi @masci, hope you are open to contributions to this repo. It's a great example project for learning Haystack.

I'd like to submit a PR on the `build.sh` script to parameterize some things that are hard coded and I have a prototype that I'm working on to learn Haystack which I may ask you to add in the coming weeks.

For now, I'm running into this permission error. Here's the command and output.

```sh
DATA_IMAGE_NAME=stephens/elasticsearch-custom ./build.sh
```

When I review the haystack container I see:

```log
[2022-12-31 19:28:41 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2022-12-31 19:28:41 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2022-12-31 19:28:41 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-12-31 19:28:41 +0000] [8] [INFO] Booting worker with pid: 8
[2022-12-31 19:28:43 +0000] [8] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/venv/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/opt/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/venv/lib/python3.10/site-packages/rest_api/application.py", line 13, in <module>
    app = get_app()
  File "/opt/venv/lib/python3.10/site-packages/rest_api/utils.py", line 28, in get_app
    from rest_api.controller import file_upload, search, feedback, document, health
  File "/opt/venv/lib/python3.10/site-packages/rest_api/controller/file_upload.py", line 20, in <module>
    indexing_pipeline: Pipeline = get_pipelines().get("indexing_pipeline", None)
  File "/opt/venv/lib/python3.10/site-packages/rest_api/utils.py", line 59, in get_pipelines
    pipelines = setup_pipelines()
  File "/opt/venv/lib/python3.10/site-packages/rest_api/pipeline/__init__.py", line 28, in setup_pipelines
    query_pipeline = Pipeline.load_from_yaml(Path(config.PIPELINE_YAML_PATH), pipeline_name=config.QUERY_PIPELINE_NAME)
  File "/opt/venv/lib/python3.10/site-packages/haystack/pipelines/base.py", line 1908, in load_from_yaml
    return cls.load_from_config(
  File "/opt/venv/lib/python3.10/site-packages/haystack/pipelines/base.py", line 1969, in load_from_config
    validate_config(pipeline_config, strict_version_check=strict_version_check)
  File "/opt/venv/lib/python3.10/site-packages/haystack/pipelines/config.py", line 245, in validate_config
    validate_schema(pipeline_config=pipeline_config, strict_version_check=strict_version_check, extras=extras)
  File "/opt/venv/lib/python3.10/site-packages/haystack/pipelines/config.py", line 302, in validate_schema
    schema = load_schema()
  File "/opt/venv/lib/python3.10/site-packages/haystack/nodes/_json_schema.py", line 423, in load_schema
    raise e
  File "/opt/venv/lib/python3.10/site-packages/haystack/nodes/_json_schema.py", line 417, in load_schema
    update_json_schema(main_only=True)
  File "/opt/venv/lib/python3.10/site-packages/haystack/nodes/_json_schema.py", line 437, in update_json_schema
    os.makedirs(destination_path, exist_ok=True)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/venv/lib/python3.10/site-packages/haystack/json-schemas'
[2022-12-31 19:28:43 +0000] [8] [INFO] Worker exiting (pid: 8)
[2022-12-31 19:28:45 +0000] [1] [INFO] Shutting down: Master
[2022-12-31 19:28:45 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by rgstephens** [comment]
If I go back to a slightly older image, `deepset/haystack:cpu-v1.12.2`, then the problem is resolved but a new issue comes up with that image. It goes into a loop where the worker is terminated.

I'm reading reports that this could be OOM or that I need to incerase the gunicorn timeout.

```log
[2022-12-31 19:44:46 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2022-12-31 19:44:46 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2022-12-31 19:44:46 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2022-12-31 19:44:46 +0000] [7] [INFO] Booting worker with pid: 7
WARNING:root:This pipeline is version 'ignore', but you're using Haystack 1.12.2
This might cause bugs and unexpected behaviors.Please check out the release notes (https://github.com/deepset-ai/haystack/releases/latest), the documentation (https://haystack.deepset.ai/components/pipelines#yaml-file-definitions) and fix your configuration accordingly.
INFO:haystack.pipelines.config:Param 'host' of component 'DocumentStore' overwritten with environment variable 'DOCUMENTSTORE_PARAMS_HOST' value 'elasticsearch'.
INFO:haystack.pipelines.config:Param 'host' of component 'DocumentStore' overwritten with environment variable 'DOCUMENTSTORE_PARAMS_HOST' value 'elasticsearch'.
INFO:haystack.pipelines.config:Param 'host' of component 'DocumentStore' overwritten with environment variable 'DOCUMENTSTORE_PARAMS_HOST' value 'elasticsearch'.
/opt/venv/lib/python3.10/site-packages/elasticsearch/connection/base.py:190: ElasticsearchDeprecationWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.
  warnings.warn(message, category=ElasticsearchDeprecationWarning)
/opt/venv/lib/python3.10/site-packages/elasticsearch/connection/http_urllib3.py:275: DeprecationWarning: HTTPResponse.getheaders() is deprecated and will be removed in urllib3 v2.1.0. Instead access HTTResponse.headers directly.
  return response.status, response.getheaders(), raw_data
INFO:haystack.modeling.utils:Using devices: CPU - Number of GPUs: 0
Downloading: 100%|██████████| 28.0/28.0 [00:00<00:00, 4.99kB/s]
Downloading: 100%|██████████| 232k/232k [00:00<00:00, 782kB/s]
Downloading: 100%|██████████| 466k/466k [00:00<00:00, 1.51MB/s]
Downloading: 100%|██████████| 493/493 [00:00<00:00, 143kB/s]
Downloading: 100%|██████████| 438M/438M [00:04<00:00, 92.4MB/s]
INFO:haystack.modeling.model.language_model:Auto-detected model language: english
Downloading: 100%|██████████| 28.0/28.0 [00:00<00:00, 55.6kB/s]
Downloading: 100%|██████████| 232k/232k [00:00<00:00, 752kB/s]
Downloading: 100%|██████████| 466k/466k [00:00<00:00, 982kB/s]
Downloading: 100%|██████████| 492/492 [00:00<00:00, 54.7kB/s]
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'DPRQuestionEncoderTokenizer'.
The class this function is called from is 'DPRContextEncoderTokenizerFast'.
Downloading: 100%|██████████| 438M/438M [00:05<00:00, 84.7MB/s]
INFO:haystack.modeling.model.language_model:Auto-detected model language: english
INFO:haystack.modeling.utils:Using devices: CPU - Number of GPUs: 0
INFO:haystack.modeling.utils:Using devices: CPU - Number of GPUs: 0
Downloading: 100%|██████████| 571/571 [00:00<00:00, 164kB/s]
INFO:haystack.modeling.model.language_model: * LOADING MODEL: 'deepset/roberta-base-squad2' (Roberta)
Downloading: 100%|██████████| 496M/496M [00:09<00:00, 52.9MB/s]
INFO:haystack.modeling.model.language_model:Auto-detected model language: english
INFO:haystack.modeling.model.language_model:Loaded 'deepset/roberta-base-squad2' (Roberta model) from model hub.
[2022-12-31 19:45:27 +0000] [1] [WARNING] Worker with pid 7 was terminated due to signal 9
[2022-12-31 19:45:27 +0000] [17] [INFO] Booting worker with pid: 17
WARNING:root:This pipeline is version 'ignore', but you're using Haystack 1.12.2
```

**Comment by masci** [comment]
The fix for the permission error was merged as part of https://github.com/deepset-ai/haystack/pull/3701 so `cpu-main` should be good again

**Comment by rgstephens** [comment]
Thanks!
