### ISSUE TITLE
Error when trying to load new data into Haystack Demo application

### ISSUE THREAD

**Issue by nickTurano** [deepset-ai/haystack-demos#22]
I have recently spun up my own version of the Haystack Explore the World Demo.  I have swapped out the data store with OpenSearch and I have used an indexing pipeline to load in my own markdown and CSV files.  

Whenever I try to query the data from those files I get an error on the frontend saying "🐞    An error occurred during the request."  There are no further details in the web console or network tracker.  In the logs for the REST backend I am seeing that it  is attempting to generate an answer, but it is unclear why the frontend is able to process this result:

```
INFO:haystack.schema:Setting the ID manually. This might cause a mismatch with the ID that would be generated from the document content and id_hash_keys value.
Inferencing Samples: 100%|██████████| 1/1 [00:08<00:00,  8.22s/ Batches]
INFO:haystack:{"request": "query='What trainings are required to setup a new project?' params={'filters': {}, 'Retriever': {'top_k': 3}, 'Reader': {'top_k': 3}, 'Query': {'debug': False}} debug=False", "response": {"query": "What trainings are required to setup a new project?", "no_ans_gap": -0.034327149391174316, "answers": ["<Answer: answer='', score=0.5485038046700377, context=None>", "<Answer: answer='process', score=0.3887302279472351, context='\"Could you please assist me to complete the requir...'>", "<Answer: answer='HTML/pdf/word-\nbased', score=0.14553304016590118, context='porting - HTML-\nbased report and logs,\nDetailed xm...'>"], "documents": ["<Document: id=a549f704cfcceb139c73c64a63950a81, content='\"Could you please assist me to complete the required trainings and process for setup a new Project\"'>", "<Document: id=bf3d4a8bb8c33fdc3ad76c4f57edfe1, content='Therefore, it\nshould be always be under consideration before making a decision on\nautomation framewo...'>", "<Document: id=210f19dbb5a8ca0052e4077d61adc570, content=' Verify user is able to view the failure message in Xray/Jira for test script\n...'>"], "root_node": "Query", "params": {"filters": {}, "Retriever": {"top_k": 3}, "Reader": {"top_k": 3}, "Query": {}}, "node_id": "Reader"}, "time": "8.25"}
```

I have tried using both a CSVConverter for my Q&A docs, and a MarkdownConverter for my Documentation.  Data from either indexing pipeline is unable to be queried.  

**FAQ Check**
- [x] Have you had a look at [our new FAQ page](https://docs.haystack.deepset.ai/docs/faq)? Yes

 - Haystack version (commit or version number): deepset/haystack:cpu-main docker image
 - DocumentStore: Opensearch
 - Reader/Retriever: haystack docker image default

**Comment by bilgeyucel** [comment]
_I moved issue to haystack-demos repository as it's related to the demo_
Hi @FasoldCS , do you have any more details to share? Which docker images are you using? 
I guess that the problem is about the UI of the demo, not about Haystack but any error/log message you have would be helpful for us to reproduce the issue.

**Comment by FasoldCS** [comment]
Hello @bilgeyucel ,
thanks for your reply!
I am using this docker-compose.yml:
---
services:
  haystack-streamlit-ui:
    image: "deepset/haystack-streamlit-ui"
    ports:
      - 8501:8501
  haystack-api:
    image: "deepset/haystack:cpu"
    volumes:
      - /some/local/path:/opt/pipelines
    ports:
      - 8009:8000
    restart: on-failure
    environment:
      - DOCUMENTSTORE_PARAMS_HOST=elasticsearch
      - PIPELINE_YAML_PATH=/opt/pipelines/pipelines.haystack-pipeline.yml
      - TOKENIZERS_PARALLELISM=false
      # Uncomment the following line to customise how much time (in seconds) a worker can spend serving a request
      # before it times out. This should include the time required to cache the models and setup the pipelines.

      # - GUNICORN_CMD_ARGS="--timeout=3000"
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.6"
    ports:
      - 9200:9200
    restart: on-failure
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    healthcheck:
        test: curl --fail http://localhost:9200/_cat/health || exit 1
        interval: 10s
        timeout: 1s
        retries: 10
---

So currently it is Haystack 1.18.0rc2.

I get this error in the UI container:
---
2023-07-20T06:52:19.013958556Z 2023-07-20 06:52:19.013 'document_id'
2023-07-20T06:52:19.013997917Z Traceback (most recent call last):
2023-07-20T06:52:19.014001567Z   File "ui/webapp.py", line 193, in main
2023-07-20T06:52:19.014004937Z     question, top_k_reader=top_k_reader, top_k_retriever=top_k_retriever
2023-07-20T06:52:19.014007947Z   File "/home/user/ui/utils.py", line 74, in query
2023-07-20T06:52:19.014011047Z     "document": [doc for doc in response["documents"] if doc["id"] == answer["document_id"]][0],
2023-07-20T06:52:19.014014557Z   File "/home/user/ui/utils.py", line 74, in <listcomp>
2023-07-20T06:52:19.014017977Z     "document": [doc for doc in response["documents"] if doc["id"] == answer["document_id"]][0],
2023-07-20T06:52:19.014021297Z KeyError: 'document_id'
---
This comes from the fact that the result from the API has that XML part in it and is not purely JSON...
Here is the JSON with the XML part included:
---
{
  "request": "query='What is the capital of Germany?' params=None debug=False",
  "response": {
    "query": "What is the capital of Germany?",
    "no_ans_gap": 18.858534812927246,
    "answers": [
      "<Answer: answer='Berlin', score=0.9377667307853699, context='d the Netherlands to the west. The nation's capita...'>",
      "<Answer: answer='Berlin', score=0.7505207657814026, context='\n\n'''Berlin''' ( , ) is the capital and largest ci...'>",
      "<Answer: answer='Berlin-Brandenburg', score=0.4750765264034271, context='ional urban area was home to about 5.2\u00a0million peo...'>",
      "<Answer: answer='Berlin', score=0.45271947979927063, context=' a partnership with the Israeli city of Kiryat Yam...'>",
      "<Answer: answer='Berlin', score=0.34971415996551514, context='3th century and at the crossing of two important h...'>",
      "<Answer: answer='', score=0.2869530100576962, context=None>",
      "<Answer: answer='Nationalities', score=0.28469300270080566, context='l registered a migration surplus of approximately ...'>",
      "<Answer: answer='Berlin', score=0.26080426573753357, context='nmental representatives and national leaders are c...'>",
      "<Answer: answer='Berlin', score=0.25885170698165894, context='became the West German capital. Following German r...'>",
      "<Answer: answer='Berlin', score=0.2278611660003662, context='the ninth most visited country in the world , with...'>"
    ],
    "documents": [
      "<Document: id=4f49f8d86257bd06b46c3e37e79998f7, content='\n\n'''Germany''' (, ), officially the '''Federal Republic of Germany''', is a country in Central Euro...'>",
      "<Document: id=70dcac7eb8f75b895292495ad6d285ca, content='Berlin is twinned with:\n\n*Los Angeles, United States (1967)\n\n*Madrid, Spain (1988)\n*Istanbul, Turkey...'>",
      "<Document: id=e6017595a8004f8d959e9bf64a0d121d, content='\n\n'''Berlin''' ( , ) is the capital and largest city of Germany by both area and population. Its 3.7...'>",
      "<Document: id=70278e6577a026eec4eee071e6ca2738, content='The country's greenhouse gas emissions per capita were the ninth highest in the EU . The German ener...'>",
      "<Document: id=78c7224634d2954beaa5e878f8f6483d, content='First documented in the 13th century and at the crossing of two important historic trade routes, Ber...'>",
      "<Document: id=431339d8e7a92b96d4c54d284617cc77, content='These include the Old National Gallery, the Bode Museum, the Pergamon Museum, the German Historical ...'>",
      "<Document: id=ea76e9c9fd5cbb68d238375ff88eaf30, content='The Federal Foreign Office and the ministries and departments of Defense, Justice and Consumer Prote...'>",
      "<Document: id=12e87e93d2fb7295d17c8102ed0c7bd7, content='Among the major German political projects of the early 21st century are the advancement of European ...'>",
      "<Document: id=3169af8495b78a076d53db0808d35e84, content='Each state () has its own constitution, and is largely autonomous in regard to its internal organisa...'>",
      "<Document: id=3357a3f413257f04601dc426270e8e44, content='Following German reunification, the center portion was reconstructed with a steel frame, and U-Bahn ...'>"
    ],
    "root_node": "Query",
    "params": {
      "Query": {},
      "Retriever": {},
      "Reader": {}
    },
    "node_id": "Reader"
  },
  "time": "18.49"
}
---

Funny thing is if I call the endpoint directly via "curl", I get a properly formatted result back...

**Comment by bilgeyucel** [comment]
Hi @FasoldCS, okay I think I understood the problem here. It's 99% about the `deepset/haystack-streamlit-ui` image. I'll make sure that we'll fix it 👍 
In the meantime, what you can do is to follow the [development instructions](https://github.com/deepset-ai/haystack-demos/tree/main/explore_the_world#development) and run the web application from the code rather than using the docker image. Let me know if you need more guidance to make it work. Also, feel free to join our Discord channel, where you can definitely get faster answers :) :https://discord.com/invite/VBpFzsgRVF
